### ISSUE TITLE
Adding XYZ layer first prevents creation of OFDS files

### ISSUE THREAD

**Issue by stevesong** [Open-Telecoms-Data/ofds-qgis-plugin#61]
If I add an XYZ layer such as Google Roads or Open Streetmap, it loads those layers as EPSG3857 (WGS84).  Trying to use the OFDS plugin after adding one of those background layers, results in an error` "Can only use OFDS with projects in the OGC:CRS84 or EPSG4326 reference system. Please change your coordinate reference system"`

Yet, if I begin by initialising OFDS and add a Google Map or OpenStreetMap afterwards, it works fine.  I guess QGIS has no problem dynamically reprojecting Google Maps / OpenStreetMap onto EPSG:3857 but the OFDS plugin balks when it detects an incompatible layer.  If we ignored this error, would QGIS automatically reproject the OFDS layers to be compatible with Google Maps/OpenStreetMap?

I am fine having to add the XYZ layer second but it would be good to have a more user-friendly error for people who end up doing this.

**Comment by duncandewhurst** [comment]
Noting that for the time being this issue is addressed by the [documentation](https://github.com/Open-Telecoms-Data/ofds-qgis-plugin/tree/schema-0-4?tab=readme-ov-file#create-a-new-ofds-project), but we can look at alternatives in a future sprint.

**Comment by kd-ods** [comment]
> > If we ignored this error, would QGIS automatically reproject the OFDS layers to be compatible with Google Maps/OpenStreetMap?
> 
> No - I'm pretty sure the project would stay in the original CRS, people would add data with X&Y values that were totally wrong in OGC::CRS84. When they exported the file they would get a JSON file that claimed it had X&Y values in OGC::CRS84 but didn't really, and when they uploaded that file to CoVE the map would show nodes and spans in totally the wrong place.

This assumption isn't correct. @stevesong is right that that QGIS automatically transforms geolocations from layer CRS settings to  the project CRS (i.e re-projecting). I tried the following (in QGIS 3.44):

**Pt1**

1. Removing the check (by commenting out lines 125 - 129 in [plugin.py](https://github.com/Open-Telecoms-Data/ofds-qgis-plugin/blob/main/ofdsqgisplugin/plugin.py) on a local branch of the plugin)
2. Starting a new project (Project CRS defaults to EPSG: 4326)
3. Adding OpenStreetMap layer (**Project CRS is** auto-changed to **EPSG: 3857** - to match the OSM layer CRS)
4. Adding the OFDS layers (Project CRS is unchanged. OFDS layers are in EPSG: 4326)
5. Importing the [Accra - Kumasi network JSON file](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/blob/0.4-dev/examples/json/network-package.json).
6. Adding another node and span to Obuasi and exporting the [updated JSON](https://gist.github.com/kd-ods/cf0ea9206c8d6d463b98608a3f786ecc)

**Pt2**

1. Starting a new project (**Project CRS defaults to** **EPSG: 4326**)
2. Adding the OFDS layers (Project CRS is unchanged. OFDS layers are in EPSG: 4326)
3. Adding OpenStreetMap layer (Project CRS is unchanged. OSM layer is in EPSG: 3857)
4. Importing the [updated JSON](https://gist.github.com/kd-ods/cf0ea9206c8d6d463b98608a3f786ecc). The nodes and spans are correctly located on the map.

My understanding is that essentially: everything works correctly (whatever the Project CRS setting) because the OFDS layers are set - as they should be according the standard - to EPSG: 4326. [Here's more about QGIS CRS and projections](https://docs.qgis.org/3.44/en/docs/user_manual/working_with_projections/working_with_projections.html).

So I *think* we can just remove the check. But I would like someone to check my understanding, @neelima-j @duncandewhurst .

**Comment by neelima-j** [comment]
From my understanding of QGIS Reprojection, the project CRS is a lens through which we see the map, and this can be anything! The layers have their inherent CRS that QGIS matches up. 

The OFDS plugin loads the OFDS layer in  EPSG: 4326. If a user loads in another layer in any other CRS,  to copy or compare, QGIS will dynamically reproject it on the fly to match your project's visual 'lens' for flawless comparison, and if you copy features from it, QGIS will automatically translate those coordinates into EPSG:4326. 

Agreeing with @kd-ods  that the check can be removed

**Comment by stevesong** [comment]
Glad to see this resolved!

**Comment by kd-ods** [comment]
In investigating this issue, I came across an instance of issue #18 . There's a risk that if we remove the CRS check without resolving #18, then people who add the OSM layer first will still have a less-than-ideal experience. 

I wonder if an alternative to removing the CRS check is to keep the check but alter its onward effect:

- If the project CRS is not EPSG: 4326 then set it to EPSG: 4326. And notify the user that the project CRS has been changed.

(In the meantime, while we decide the best way to resolve this, @neelima-j kindly informed me that there's a quick way in the QGIS UI to alter the project CRS. In the bottom right, you can click the current CRS info to open the CRS settings:

<img width="350" alt="Image" src="https://github.com/user-attachments/assets/824fb984-f0a5-402c-88c9-0f4e4977f703" />

)

**Comment by kd-ods** [comment]
@Bjwebb - I'm testing the work on the bw-set-crs branch. 

The only issue is that the notification message about the CRS change is then hidden by the dialog for saving the OFDS geopackage:

<img width="1289" height="250" alt="Image" src="https://github.com/user-attachments/assets/b1863c3c-0c7a-4d41-bce3-0e410d5885b2" />

.
.
And then it disappears before the user has a chance to read it.

I suggest we remove the notification message from the CRS check code. Instead, could we add a generic notification message after the OFDS layers are actually added, saying "OFDS layers added. Project CRS is EPSG:4326." (Which will be true whether or not the project CRS has been programmatically changed.)

If you think that will work from a usability perspective, let's try it.

**Comment by duncandewhurst** [comment]
I tested the fix on the bw-set-crs branch on QGIS 4.0 and there were no error messages (neither the one discussed in this issue, nor the one in #18).

**Comment by neelima-j** [comment]
Tested bw-set-crs branch on QGIS 4.0: 
As @kd-ods mentioned the INFO message " INFO    Can only use OFDS with projects in the OGC:CRS84 or EPSG:4326 coordinate reference system (CRS). Automatically switching to EPSG:4326." is seen and then the save dialog covers it. 

This message can be viewed again in the Messages tab.  

<img width="842" height="357" alt="Image" src="https://github.com/user-attachments/assets/d29751ba-3a48-4672-9448-7b750e3aefbc" />

As it is just an info message that needs no action from the user, we can keep it for completeness, and the user may see it in the messages tab.

**Comment by Bjwebb** [comment]
> I suggest we remove the notification message from the CRS check code. Instead, could we add a generic notification message after the OFDS layers are actually added, saying "OFDS layers added. Project CRS is EPSG:4326." (Which will be true whether or not the project CRS has been programmatically changed.)

If we do this, it's quite easy to make the text say "OFDS layers addded." or "OFDS layers addded. Automatically switching project CRS to EPSG:4326." as appropriate.

**Comment by kd-ods** [comment]
> As it is just an info message that needs no action from the user, we can keep it for completeness

We know that the message needs no action from the user, but they won't know that until they can read it. (I'd rather not rely on them knowing about the message log feature... mainly because I didn't know about it until you mentioned it ;-))

> I suggest we remove the notification message from the CRS check code. Instead, could we add a generic notification message after the OFDS layers are actually added, saying "OFDS layers added. Project CRS is EPSG:4326." (Which will be true whether or not the project CRS has been programmatically changed.)

@neelima-j - do you have any concern about this alternative suggestion?

**Comment by kd-ods** [comment]
> If we do this, it's quite easy to make the text say "OFDS layers addded." or "OFDS layers addded. Automatically switching project CRS to EPSG:4326." as appropriate.

@Bjwebb - brilliant. Let's do that!

**Comment by Bjwebb** [comment]
> > If we do this, it's quite easy to make the text say "OFDS layers addded." or "OFDS layers addded. Automatically switching project CRS to EPSG:4326." as appropriate.
> 
> [@Bjwebb](https://github.com/Bjwebb) - brilliant. Let's do that!

I've implemented this on a new branch: [bw-set-crs-fix-msg](https://github.com/Open-Telecoms-Data/ofds-qgis-plugin/tree/bw-set-crs-fix-msg).

**Comment by kd-ods** [comment]
Thanks, @Bjwebb - that's working well on 3.44. @neelima-j - over to you for testing on 4.0.

**Comment by neelima-j** [comment]
Tested on QGIS 4.0 

The CRS automatically changes to 4326 as I save the OFDS layer. I see the INFO message    "OFDS layers addded. Automatically switching project CRS to EPSG:4326."

All good.

**Comment by kd-ods** [comment]
@Bjwebb - we tested the work on [bw-set-crs-fix-msg](https://github.com/Open-Telecoms-Data/ofds-qgis-plugin/tree/bw-set-crs-fix-msg) and it's good for a user perspective. Will you [log this](https://github.com/Open-Telecoms-Data/ofds-qgis-plugin/blob/bw-set-crs-fix-msg/metadata.txt) as a patch release and update the qgis repo?

**Comment by kd-ods** [comment]
This has now been fixed and released: https://plugins.qgis.org/plugins/ofds_studio/#plugin-versions. Thanks, @Bjwebb!

Final wrap-up is to update the repo changelog to match the release one. Will close this issue once that's complete.
